Yii Access Control Lists: Util Class Reference
Util Class Reference
Utility Class
Static Public Member Functions
static addGroupRestr ($relation, $restrictions)
static generateInStatement ($options)
Generates a database-IN-statement out of the given options.
static getByIdentifier ($identifier)
Retrieves the requested object by the given identifier (an object) Will throw an exception if the model-name is invalid but return NULL if the identifier doesn't match any instance.
static getByIdentifierGraceful ($identifier)
Behaves just as getByIdentifier but returns the object itself if no associated record is found.
static getDataBaseType ($obj)
Returns the database-type of the given object.
static getIdsOfObjects ($objects)
Extracts the IDs of the given bunch of objects and returns them in an indexed arry.
static getNodeNameOfObject (AclObject $obj)
Returns the class-name of the node belonging to the given Object.
static rep ($string, $array)
Replaces all occurences of a key in $string with the keys value in $array.
Detailed Description
Utility Class
Author:
dispy <dispyfree@googlemail.com> LGPLv2
Definition at line 8 of file Util.php.
Member Function Documentation
static Util::addGroupRestr ($ relation, $ restrictions) [static]
Definition at line 134 of file Util.php.
References RestrictedActiveRecordBehavior\addGroupRestriction().
static Util::generateInStatement ($ options) [static]
Generates a database-IN-statement out of the given options.
Parameters:
array[string] $options
Return values:
string the in-statement
Definition at line 59 of file Util.php.
Referenced by PmAro\deny(), PmAclObject\getDirectChildNodes(), RestrictedActiveRecord\getDirectlyPermitted(), RestrictedActiveRecordBehavior\getDirectlyPermitted(), PmAclObject\getDirectParentNodes(), RestrictedActiveRecord\getPermissionsWithBiz(), PmAro\grant(), and PmAclObject\is().
static Util::getByIdentifier ($ identifier) [static]
Retrieves the requested object by the given identifier (an object) Will throw an exception if the model-name is invalid but return NULL if the identifier doesn't match any instance.
Parameters:
AclObject identifier [model, foreign_key]
Definition at line 93 of file Util.php.
static Util::getByIdentifierGraceful ($ identifier) [static]
Behaves just as getByIdentifier but returns the object itself if no associated record is found.
Parameters:
AclObject $identifier
Return values:
mixed
Definition at line 110 of file Util.php.
Referenced by PmAclObject\callBusinessRule(), AclObject\loadObjectsStatic(), and PmAro\may().
static Util::getDataBaseType ($ obj) [static]
Returns the database-type of the given object.
Parameters:
AclObject $obj
Return values:
string
Exceptions:
InvalidArgumentException
Definition at line 16 of file Util.php.
References Strategy\getClass().
Referenced by PmPermission\deleteByObject(), AclObject\getChildObjects(), PmAclObject\getDirectChildNodes(), PmAclObject\getDirectParentNodes(), AclObject\getParentObjects(), PmAclObject\getType(), PmAclObject\is(), AclObject\loadObjectsStatic(), and PmAclNode\removeFullRecursively().
static Util::getIdsOfObjects ($ objects) [static]
Extracts the IDs of the given bunch of objects and returns them in an indexed arry.
Parameters:
array $objects
Return values:
array[int]
Definition at line 79 of file Util.php.
Referenced by PmAro\deny(), and PmAro\grant().
static Util::getNodeNameOfObject (AclObject $ obj) [static]
Returns the class-name of the node belonging to the given Object.
Parameters:
PmAclObject $obj
Return values:
string
Exceptions:
InvalidArgumentException
Definition at line 39 of file Util.php.
References Strategy\getClass().
Referenced by PmAclObject\beforeDelete(), PmAclObject\createNode(), PmAclObject\getDirectChildNodes(), PmAclObject\getDirectParentNodes(), PmAclObject\getFreeNodes(), AclObject\getNodes(), PmAclObject\getPaths(), PmAclObject\is(), and PmAclObject\leave().
static Util::rep ($ string, $ array) [static]
Replaces all occurences of a key in $string with the keys value in $array.
Parameters:
string $string the string to replace in
array $array the keys/values
Definition at line 126 of file Util.php.
Referenced by RestrictedActiveRecordBehavior\generateAccessCheck().
The documentation for this class was generated from the following file:
Util.php