Yii Access Control Lists: PmPathManager Class Reference
PmPathManager Class Reference
The Path-Manager provides basic functionality for working with paths such as:
Static Public Member Functions
static appendToPath ($path, $id)
Appends the given ID (denoting an element) to the given path.
static buildMultiplePathCondition ($field, $paths, $additionalCondition= '')
Builds an sql-condition like: ($field LIKE [...] [AND condition]) OR ($field LIKE [...] [AND condition]) for all the given paths.
static getParentPath ($path)
Returns the parent path of the given path and the ID of the parent.
static getSeparator ()
Detailed Description
The Path-Manager provides basic functionality for working with paths such as:
building paths
splitting the paths up into their ids
building Query-conditions
Author:
dispy <dispyfree@googlemail.com> LGPLv2
Definition at line 12 of file PmPathManager.php.
Member Function Documentation
static PmPathManager::appendToPath ($ path, $ id) [static]
Appends the given ID (denoting an element) to the given path.
Parameters:
string $path
string $id
Return values:
string the full path including the new element
Definition at line 21 of file PmPathManager.php.
References getSeparator().
Referenced by PmAclNode\branchNodeSubTree(), PmAclObject\createNode(), PmAclNode\generateDirectChildrenCondition(), PmAclObject\getDirectChildNodes(), PmAclNode\getOwnPath(), PmAclObject\getPaths(), and PmAclNode\removeFullRecursively().
static PmPathManager::buildMultiplePathCondition ($ field, $ paths, $ additionalCondition = '') [static]
Builds an sql-condition like: ($field LIKE [...] [AND condition]) OR ($field LIKE [...] [AND condition]) for all the given paths.
Parameters:
string $field the field to match (for example: path)
array[string] $paths
string $additionalCondition If given, this will be used as an additional condition to every single path-like-condition (bound with and) Occurences of :path will be replaced with the provided path
Todo:
: to be checked if the order is correct in all uses (a regexp b => hierarchy?)
Return values:
string the condition
Definition at line 60 of file PmPathManager.php.
Referenced by PmAclObject\beforeDelete(), PmPermission\deleteByObject(), PmAclObject\is(), and PmAclObject\leave().
static PmPathManager::getParentPath ($ path) [static]
Returns the parent path of the given path and the ID of the parent.
Parameters:
array[string path, string ID] $path
Definition at line 32 of file PmPathManager.php.
References getSeparator().
Referenced by PmAclNode\generateDirectParentCondition(), and PmAclObject\getDirectParentNodes().
static PmPathManager::getSeparator () [static]
Definition at line 76 of file PmPathManager.php.
Referenced by appendToPath(), PmAclObject\buildTreeQueryCondition(), PmAclObject\createNode(), getParentPath(), and PmAclNode\removeFullRecursively().
The documentation for this class was generated from the following file:
PmPathManager.php