Yii Access Control Lists: PmAclObject Class Reference
PmAclObject Class Reference
The specialization of the general AclObject.
Public Member Functions
addPositionCheck ($positions, $type, $table= 't', $dir= 'asc', $fieldPostfix= '_path')
$dir = 'asc': Builds a single SQL-statement comprising all given positions and their parents This SQL-statement will match all those rows being located above the given positions including themselves
beforeDelete ()
Processes post-deletion tasks.
fetchComprisedPositions ()
Fetches and returns positions of all nodes of this object which denote them In this case, it's really easy because we've done that anyway :)
getDirectChildNodes (AclObject $child=NULL)
Returns all of the (direct) AclNodes whose parent AclNode is a node of this AclObject.
getDirectParentNodes (AclObject $parent=NULL)
Returns all of the (direct) AclNodes whose child AclNode is a node of this AclObject.
getFreeNodes ()
Returns all of the AclNodes of this object which do not have a parent yet.
getPaths ()
Fetches all Paths of the nodes of this object.
getType ()
is ($obj)
Checks whether this object is somehow a child of the given object.
join ($obj, $byPassCheck=false)
Joins the given object (now called: group)
leave ($obj, $byPassCheck=false)
Leaves the given group.
Static Public Member Functions
static buildTreeQueryCondition ($source, $destination, $disableInheritance=false)
Builds (string) condition which matches all destinations, which are children of source field should be either aco or aro.
Protected Member Functions
callBusinessRule ($rule, $obj, $action)
This packs the object and this object itself in the proper array and calls the specific business-rule taking care of aro/aco specific syntax.
callSpecificBusinessRule ($rule, $arr, $action)
This takes care of the aro/aco specifis for calling business-rules.
checkRelationChange ($type, $obj)
This function checks if the current aro-object may let this object join or leave the given object If not, it throws an exception: otherwise it returns true.
createNode ($parent=NULL)
Creates a new node of this collection This new node will be a children of the given AclNode.
Detailed Description
The specialization of the general AclObject.
This class implements the path-materialization-specific/optimized position- and rights-operations
Author:
dispy <dispyfree@googlemail.com> LGPLv2
Definition at line 11 of file PmAclObject.php.
Member Function Documentation
PmAclObject::addPositionCheck ($ positions, $ type, $ table = 't', $ dir = 'asc', $ fieldPostfix = '_path')
$dir = 'asc': Builds a single SQL-statement comprising all given positions and their parents This SQL-statement will match all those rows being located above the given positions including themselves
$dir = 'desc' The same, but with all the positions located below the given positions or equal to them.
Parameters:
array $positions All positions to include in our statement
string $type aco/aro
string $table the table comprising the map between objects and permissions
string $fieldPostfix the postfix of the field (default: "_path" (suitable for the fields in the permission-table)
Return values:
string the finished SQL-statement
Reimplemented from AclObject.
Definition at line 94 of file PmAclObject.php.
Referenced by PmAro\may().
PmAclObject::beforeDelete ()
Processes post-deletion tasks.
Definition at line 222 of file PmAclObject.php.
References PmPathManager\buildMultiplePathCondition(), PmPermission\deleteByObject(), Util\getNodeNameOfObject(), and getPaths().
static PmAclObject::buildTreeQueryCondition ($ source, $ destination, $ disableInheritance = false) [static]
Builds (string) condition which matches all destinations, which are children of source field should be either aco or aro.
Parameters:
array $source array('field' => '', 'table' => '')
array $destination array('field' => '', 'table' => '')
boolean $disableInheritance if set to true, no inheritance will be used, that means no node will acquire the rights of it's parent
Definition at line 53 of file PmAclObject.php.
References $source, and PmPathManager\getSeparator().
PmAclObject::callBusinessRule ($ rule, $ obj, $ action) [protected]
This packs the object and this object itself in the proper array and calls the specific business-rule taking care of aro/aco specific syntax.
Parameters:
string the Rule
mixed the given object
string the action
Definition at line 415 of file PmAclObject.php.
References Util\getByIdentifierGraceful().
Referenced by is().
PmAclObject::callSpecificBusinessRule ($ rule, $ arr, $ action) [abstract, protected]
This takes care of the aro/aco specifis for calling business-rules.
Parameters:
string the Rule
arr array('child' and 'father')
string the action
Reimplemented in PmAro, and PmAco.
PmAclObject::checkRelationChange ($ type, $ obj) [protected]
This function checks if the current aro-object may let this object join or leave the given object If not, it throws an exception: otherwise it returns true.
Exceptions:
RuntimeException
Parameters:
string $type either "join" or "leave"
mixed $obj the object to join/leave
Return values:
boolean true if succeeded
Definition at line 325 of file PmAclObject.php.
References Strategy\get(), and RestrictedActiveRecord\getUser().
Referenced by join(), and leave().
PmAclObject::createNode ($ parent = NULL) [protected]
Creates a new node of this collection This new node will be a children of the given AclNode.
Parameters:
AclNode $parent parent of the new node, if NULL, it has no parent
Return values:
AclNode the new node
Reimplemented from AclObject.
Definition at line 126 of file PmAclObject.php.
References PmPathManager\appendToPath(), Util\getNodeNameOfObject(), and PmPathManager\getSeparator().
Referenced by join().
PmAclObject::fetchComprisedPositions ()
Fetches and returns positions of all nodes of this object which denote them In this case, it's really easy because we've done that anyway :)
Return values:
array[string]
Reimplemented from AclObject.
Definition at line 76 of file PmAclObject.php.
References getPaths().
PmAclObject::getDirectChildNodes (AclObject $ child = NULL)
Returns all of the (direct) AclNodes whose parent AclNode is a node of this AclObject.
If the $child AclObject is specified, only nodes having the given AclObject as owner will be returned.
public
Parameters:
AclObject child
Integer
Return values:
array[AclNode]
Reimplemented from AclObject.
Definition at line 157 of file PmAclObject.php.
References PmPathManager\appendToPath(), Util\generateInStatement(), Util\getDataBaseType(), and Util\getNodeNameOfObject().
PmAclObject::getDirectParentNodes (AclObject $ parent = NULL)
Returns all of the (direct) AclNodes whose child AclNode is a node of this AclObject.
If the $child AclObject is specified, only nodes having the given AclObject as owner will be returned.
public
Parameters:
AclObject child
Integer
Return values:
array[AclNode]
Reimplemented from AclObject.
Definition at line 192 of file PmAclObject.php.
References Util\generateInStatement(), Util\getDataBaseType(), Util\getNodeNameOfObject(), PmPathManager\getParentPath(), and getPaths().
PmAclObject::getFreeNodes ()
Returns all of the AclNodes of this object which do not have a parent yet.
public
Parameters:
AclObject object
Return values:
array[AclNode]
Reimplemented from AclObject.
Definition at line 21 of file PmAclObject.php.
References Util\getNodeNameOfObject().
PmAclObject::getPaths ()
Fetches all Paths of the nodes of this object.
Return values:
array[string] the paths of the nodes
Definition at line 32 of file PmAclObject.php.
References PmPathManager\appendToPath(), and Util\getNodeNameOfObject().
Referenced by beforeDelete(), fetchComprisedPositions(), getDirectParentNodes(), and PmAro\may().
PmAclObject::getType ()
Return values:
string the type of this object ('Aro' or 'Aco')
Definition at line 434 of file PmAclObject.php.
References Util\getDataBaseType().
Referenced by is(), join(), and leave().
PmAclObject::is ($ obj)
Checks whether this object is somehow a child of the given object.
Parameters:
mixed $obj
Return values:
boolean
Reimplemented from AclObject.
Definition at line 357 of file PmAclObject.php.
References AclObject\beforeIs(), PmPathManager\buildMultiplePathCondition(), callBusinessRule(), Util\generateInStatement(), Strategy\get(), Util\getDataBaseType(), Util\getNodeNameOfObject(), getType(), BusinessRules\listBusinessAliases(), and AclObject\loadObjectStatic().
PmAclObject::join ($ obj, $ byPassCheck = false)
Joins the given object (now called: group)
Parameters:
mixed $obj
boolean $byPassCheck whether to bypass the permission-check
Return values:
boolean
Definition at line 249 of file PmAclObject.php.
References AclObject\beforeJoin(), checkRelationChange(), createNode(), getType(), and AclObject\loadObjectStatic().
PmAclObject::leave ($ obj, $ byPassCheck = false)
Leaves the given group.
Parameters:
mixed $obj
boolean $byPassCheck whether to bypass the permission-check
Return values:
boolean
Definition at line 281 of file PmAclObject.php.
References AclObject\beforeLeave(), PmPathManager\buildMultiplePathCondition(), checkRelationChange(), Util\getNodeNameOfObject(), getType(), and AclObject\loadObjectStatic().
The documentation for this class was generated from the following file:
PmAclObject.php