Yii Access Control Lists: RequestingActiveRecord Class Reference
RequestingActiveRecord Class Reference
RequestingActiveRecord Class File.
Public Member Functions
afterSave ()
This method takes care to associate an ARO-collection with this one.
beforeDelete ()
This method takes care that every associated ACL-objects are properly removed.
deny ($obj, $actions)
Denies the object denoted by the $obj-identifier the given actions.
grant ($obj, $actions, $byPassCheck=false)
Grants the object denoted by the $obj-identifier the given actions.
may ($obj, $action)
Looks up if the user is granted a specific action to the given object.
Protected Member Functions
loadAro ()
Loads the associated Aro_Object.
Protected Attributes
AclObject $aro = NULL
Serves as a temporary space for the associated Aro-Object.
Detailed Description
RequestingActiveRecord Class File.
This class serves as the base class for all "actors" in the program who have to per form actions on other objects
Author:
dispy <dispyfree@googlemail.com> LGPLv2
Definition at line 12 of file RequestingActiveRecord.php.
Member Function Documentation
RequestingActiveRecord::afterSave ()
This method takes care to associate an ARO-collection with this one.
Parameters:
CEvent $evt
Definition at line 86 of file RequestingActiveRecord.php.
References $aro, and Strategy\getClass().
RequestingActiveRecord::beforeDelete ()
This method takes care that every associated ACL-objects are properly removed.
Definition at line 101 of file RequestingActiveRecord.php.
References $aro, and Strategy\getClass().
RequestingActiveRecord::deny ($ obj, $ actions)
Denies the object denoted by the $obj-identifier the given actions.
Parameters:
type $obj the object identifier
array $actions the actions to deny
Return values:
bool
Definition at line 76 of file RequestingActiveRecord.php.
References loadAro().
RequestingActiveRecord::grant ($ obj, $ actions, $ byPassCheck = false)
Grants the object denoted by the $obj-identifier the given actions.
Parameters:
type $obj the object identifier
array $actions the actions to grant
bool $byPassCheck Whether to bypass the additional grant-check
Return values:
bool
Definition at line 60 of file RequestingActiveRecord.php.
References loadAro().
RequestingActiveRecord::loadAro () [protected]
Loads the associated Aro_Object.
Exceptions:
RuntimeException
Definition at line 23 of file RequestingActiveRecord.php.
References Strategy\get(), and Strategy\getClass().
Referenced by deny(), grant(), and may().
RequestingActiveRecord::may ($ obj, $ action)
Looks up if the user is granted a specific action to the given object.
Parameters:
string | array $obj The object to be checked
string $action the action to be performed
Return values:
bool true if access is granted, false otherwise
Definition at line 48 of file RequestingActiveRecord.php.
References loadAro().
Member Data Documentation
AclObject RequestingActiveRecord::$aro = NULL [protected]
Serves as a temporary space for the associated Aro-Object.
Definition at line 17 of file RequestingActiveRecord.php.
Referenced by afterSave(), and beforeDelete().
The documentation for this class was generated from the following file:
RequestingActiveRecord.php