Yii Access Control Lists: AclNode Class Reference
AclNode Class Reference
AclNode This is the base class for all Nodes of the trees, providing basic functionality.
Public Member Functions
__clone ()
afterDelete ()
Runs post-deletion errands.
afterSave ()
This will take over the permissions of another node belonging to the same AclObject, if the record is a new one.
branchNodeSubTree ($source, $destination)
Copies all children of $source recursively into $destination This branching is necessary because: If an AclObject is a child of another one, every AclNode of the parent object has to have one AclNode of the child AclObject as it's child (this is due to the lookup-mechanism this extension uses) If a new AclNode is created (for example because the parent object itself joins another object), the subtree of an existing node is copied to the new node.
getDirectChildren ()
Returns all the direct children of the given Node.
getDirectParents ()
Returns the direct parent AclNodes of this node.
Protected Member Functions
generateDirectChildrenCondition ()
Generates the condition matching the direct AclNodes of this node.
generateDirectParentCondition ()
Generates the condition matching the direct parent AclNodes of this node.
removeFullRecursively ()
Removes all child-nodes and their associated permissions.
takeOverPermissions ($node)
This method copies all permissions assigned to another AclNode-Object of the same AclObject.
takeOverSubTree (PmAclNode $node)
Copies the subtree of the given other node of the same object to this new node.
Detailed Description
AclNode This is the base class for all Nodes of the trees, providing basic functionality.
Author:
dispy <dispyfree@googlemail.com> * LGPLv2
Definition at line 10 of file AclNode.php.
Member Function Documentation
AclNode::__clone () [abstract]
Reimplemented in PmAclNode.
AclNode::afterDelete ()
Runs post-deletion errands.
Definition at line 34 of file AclNode.php.
References removeFullRecursively().
AclNode::afterSave ()
This will take over the permissions of another node belonging to the same AclObject, if the record is a new one.
Definition at line 15 of file AclNode.php.
References takeOverPermissions(), and takeOverSubTree().
AclNode::branchNodeSubTree ($ source, $ destination) [abstract]
Copies all children of $source recursively into $destination This branching is necessary because: If an AclObject is a child of another one, every AclNode of the parent object has to have one AclNode of the child AclObject as it's child (this is due to the lookup-mechanism this extension uses) If a new AclNode is created (for example because the parent object itself joins another object), the subtree of an existing node is copied to the new node.
In fact "copied" is the wrong term, because each node isn't cloned but a surrogate is created which is in fact another object - but a node of the same AclObject having the same children as the original one.
public
Parameters:
AclNode source
AclNode destination
Return values:
int the number of branched nodes (recursive!)
Reimplemented in PmAclNode.
Referenced by takeOverSubTree().
AclNode::generateDirectChildrenCondition () [abstract, protected]
Generates the condition matching the direct AclNodes of this node.
Return values:
array(string,array) the first is the condition, the second one the params
Reimplemented in PmAclNode.
Referenced by getDirectChildren().
AclNode::generateDirectParentCondition () [abstract, protected]
Generates the condition matching the direct parent AclNodes of this node.
Return values:
array(string,array) the first is the condition, the second one the params
Reimplemented in PmAclNode.
Referenced by getDirectParents().
AclNode::getDirectChildren ()
Returns all the direct children of the given Node.
public
Return values:
array[AclNode]
Definition at line 100 of file AclNode.php.
References generateDirectChildrenCondition().
AclNode::getDirectParents ()
Returns the direct parent AclNodes of this node.
public
Parameters:
AclNode node
Return values:
array[AclNode]
Definition at line 112 of file AclNode.php.
References generateDirectParentCondition().
AclNode::removeFullRecursively () [abstract, protected]
Removes all child-nodes and their associated permissions.
Exceptions:
RuntimeException
Reimplemented in PmAclNode.
Referenced by afterDelete().
AclNode::takeOverPermissions ($ node) [abstract, protected]
This method copies all permissions assigned to another AclNode-Object of the same AclObject.
Parameters:
AclNode the node to take the permissions from
Reimplemented in PmAclNode.
Referenced by afterSave().
AclNode::takeOverSubTree (PmAclNode $ node) [protected]
Copies the subtree of the given other node of the same object to this new node.
Parameters:
PmAclNode $node the node to take subtree from
Definition at line 59 of file AclNode.php.
References branchNodeSubTree().
Referenced by afterSave().
The documentation for this class was generated from the following file:
AclNode.php