Yii Access Control Lists: Strategy Class Reference
Strategy Class Reference
This class manages the strategy used for the tree as well as the includes and provides the strategy-specific class-names.
Static Public Member Functions
static get ($propName)
Returns the given property of the strategy-config.
static getClass ($className)
Gets the class-Name according to the chosen strategy.
static initialize ()
Static Public Attributes
static string $strategy = 'nestedSet.pathMaterialization'
This defines the strategy to use.
Static Protected Member Functions
static createShortcutClasses ()
Just generates "AGroup" and "RGroup" aka "AcessGroup" and "RequestGroup" dynamically.
Static Protected Attributes
static $config = NULL
static $initialized = false
static string $location = 'application.modules.acl.'
Assuming you put it there...
Detailed Description
This class manages the strategy used for the tree as well as the includes and provides the strategy-specific class-names.
Author:
dispy <dispyfree@googlemail.com> LGPLv2
Definition at line 10 of file Strategy.php.
Member Function Documentation
static Strategy::createShortcutClasses () [static, protected]
Just generates "AGroup" and "RGroup" aka "AcessGroup" and "RequestGroup" dynamically.
Definition at line 75 of file Strategy.php.
Referenced by initialize().
static Strategy::get ($ propName) [static]
Returns the given property of the strategy-config.
Parameters:
string $propName they key of the property
Return values:
mixed the value
Definition at line 66 of file Strategy.php.
References $config, and initialize().
Referenced by PmAro\checkPermissionChange(), PmAclObject\checkRelationChange(), RestrictedActiveRecord\generateAccessCheck(), RestrictedActiveRecordBehavior\generateAroPositionCheck(), AclObjectBehavior\getAutoJoins(), RestrictedActiveRecord\getPermissionsWithBiz(), PmAclObject\is(), RequestingActiveRecord\loadAro(), RequestingActiveRecordBehavior\loadObject(), AclObject\loadObjectsStatic(), PmAro\may(), and RestrictedActiveRecord\mayGenerally().
static Strategy::getClass ($ className) [static]
Gets the class-Name according to the chosen strategy.
Parameters:
string $className
Return values:
string the resulting class-Name for the strategy
Definition at line 47 of file Strategy.php.
References $config, and initialize().
Referenced by RequestingActiveRecord\afterSave(), RequestingActiveRecordBehavior\afterSave(), RestrictedActiveRecord\afterSave(), RestrictedActiveRecordBehavior\afterSave(), RequestingActiveRecord\beforeDelete(), RequestingActiveRecordBehavior\beforeDelete(), RestrictedActiveRecord\beforeDelete(), RestrictedActiveRecordBehavior\beforeDelete(), RestrictedActiveRecord\generateAccessCheck(), RestrictedActiveRecordBehavior\generateAccessCheck(), RestrictedActiveRecordBehavior\generateAroPositionCheck(), Util\getDataBaseType(), RestrictedActiveRecord\getDirectlyPermitted(), RestrictedActiveRecordBehavior\getDirectlyPermitted(), Util\getNodeNameOfObject(), RestrictedActiveRecord\getUser(), ExtAccessRule\isRoleMatched(), RequestingActiveRecord\loadAro(), RequestingActiveRecordBehavior\loadObject(), AclObject\loadObjectsStatic(), and Permission\relations().
static Strategy::initialize () [static]
Definition at line 26 of file Strategy.php.
References $config, $config, $strategy, and createShortcutClasses().
Referenced by get(), getClass(), and AclModule\init().
Member Data Documentation
Strategy::$config = NULL [static, protected]
Definition at line 24 of file Strategy.php.
Referenced by initialize().
Strategy::$initialized = false [static, protected]
Definition at line 18 of file Strategy.php.
string Strategy::$location = 'application.modules.acl.' [static, protected]
Assuming you put it there...
change it otherwise ^^
Definition at line 23 of file Strategy.php.
string Strategy::$strategy = 'nestedSet.pathMaterialization' [static]
This defines the strategy to use.
It's your duty to take care that all requirements (e.g. database tables) exist
Definition at line 16 of file Strategy.php.
Referenced by initialize().
The documentation for this class was generated from the following file:
Strategy.php