Yii Access Control Lists: PmAro Class Reference
PmAro Class Reference
Public Member Functions
attributeLabels ()
deny ($obj, $actions, $byPassCheck=false)
Denies the given actions to the given object.
grant ($obj, $actions, $byPassCheck=false)
Grants the given actions to the given object.
may ($originalObj, $actions)
Checks whether the this object may perform all of the given actions on the given object.
relations ()
rules ()
tableName ()
Static Public Member Functions
static model ($className=__CLASS__)
Returns the static model of the specified AR class.
Protected Member Functions
callSpecificBusinessRule ($rule, $arr, $action)
This takes care of the aro/aco specifis for calling business-rules.
checkPermissionChange ($type, $obj, $actions)
This function checks whether the permission-change of the given type is permitted with respect to the given object and the actions If not, it throws an exception: otherwise it returns true.
Detailed Description
Definition at line 16 of file PmAro.php.
Member Function Documentation
PmAro::attributeLabels ()
Return values:
array customized attribute labels (name=>label)
Definition at line 287 of file PmAro.php.
PmAro::callSpecificBusinessRule ($ rule, $ arr, $ action) [protected]
This takes care of the aro/aco specifis for calling business-rules.
Parameters:
string the Rule
arr array('child' and 'father')
string the action
Reimplemented from PmAclObject.
Definition at line 237 of file PmAro.php.
References BusinessRules\fulfillsBusinessRule().
PmAro::checkPermissionChange ($ type, $ obj, $ actions) [protected]
This function checks whether the permission-change of the given type is permitted with respect to the given object and the actions If not, it throws an exception: otherwise it returns true.
Exceptions:
RuntimeException
Parameters:
string $type either "grant" or "deny"
mixed $obj the object to change the permission on
array $actions the actions to grant/deny
Return values:
boolean true if succeeded
Definition at line 121 of file PmAro.php.
References Strategy\get(), and RestrictedActiveRecord\getUser().
Referenced by deny(), and grant().
PmAro::deny ($ obj, $ actions, $ byPassCheck = false)
Denies the given actions to the given object.
Parameters:
mixed $obj any valid identifier
mixed $actions the actions to deny
bool $byPassCheck Whether to bypass the additional deny-check
Return values:
type
Definition at line 80 of file PmAro.php.
References checkPermissionChange(), Util\generateInStatement(), Util\getIdsOfObjects(), AclObject\getNodes(), AclObject\loadObject(), model(), and Action\translateActions().
PmAro::grant ($ obj, $ actions, $ byPassCheck = false)
Grants the given actions to the given object.
Parameters:
mixed $obj any valid identifier
mixed $actions the actions to grant
bool $byPassCheck Whether to bypass the additional grant-check
Return values:
type
Definition at line 26 of file PmAro.php.
References checkPermissionChange(), Util\generateInStatement(), Util\getIdsOfObjects(), AclObject\getNodes(), AclObject\loadObject(), model(), and Action\translateActions().
PmAro::may ($ originalObj, $ actions)
Checks whether the this object may perform all of the given actions on the given object.
Parameters:
mixed $obj
mixed $actions
boolean true if it may, otherwise false
Definition at line 172 of file PmAro.php.
References PmAclObject\addPositionCheck(), RestrictedActiveRecord\checkBirPermission(), Strategy\get(), Util\getByIdentifierGraceful(), PmAclObject\getPaths(), AclObject\loadObject(), RestrictedActiveRecord\mayGenerally(), model(), and Action\translateActions().
static PmAro::model ($ className = __CLASS__) [static]
Returns the static model of the specified AR class.
Parameters:
string $className active record class name.
Return values:
PM_Aco the static model class
Definition at line 247 of file PmAro.php.
Referenced by deny(), grant(), and may().
PmAro::relations ()
Return values:
array relational rules.
Definition at line 274 of file PmAro.php.
PmAro::rules ()
Return values:
array validation rules for model attributes.
Definition at line 263 of file PmAro.php.
PmAro::tableName ()
Return values:
string the associated database table name
Definition at line 255 of file PmAro.php.
The documentation for this class was generated from the following file:
PmAro.php