Yii Access Control Lists: Permission Class Reference
Permission Class Reference
Public Member Functions
__clone ()
Clones the object - resets the ID so that it is in fact a new object in the database also.
attributeLabels ()
relations ()
rules ()
search ()
Retrieves a list of models based on the current search/filter conditions.
tableName ()
Static Public Member Functions
static model ($className=__CLASS__)
Returns the static model of the specified AR class.
Detailed Description
Definition at line 26 of file Permission.php.
Member Function Documentation
Permission::__clone ()
Clones the object - resets the ID so that it is in fact a new object in the database also.
Definition at line 113 of file Permission.php.
Permission::attributeLabels ()
Return values:
array customized attribute labels (name=>label)
Definition at line 76 of file Permission.php.
static Permission::model ($ className = __CLASS__) [static]
Returns the static model of the specified AR class.
Parameters:
string $className active record class name.
Return values:
Permission the static model class
Definition at line 34 of file Permission.php.
Referenced by PmPermission\deleteByObject(), RestrictedActiveRecord\generateAccessCheck(), RestrictedActiveRecordBehavior\generateAccessCheck(), RestrictedActiveRecord\getDirectlyPermitted(), RestrictedActiveRecordBehavior\getDirectlyPermitted(), RestrictedActiveRecord\getPermissionsWithBiz(), and PmAclNode\removeFullRecursively().
Permission::relations ()
Return values:
array relational rules.
Definition at line 61 of file Permission.php.
References Strategy\getClass().
Permission::rules ()
Return values:
array validation rules for model attributes.
Definition at line 50 of file Permission.php.
Permission::search ()
Retrieves a list of models based on the current search/filter conditions.
Return values:
CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
Definition at line 92 of file Permission.php.
Permission::tableName ()
Return values:
string the associated database table name
Definition at line 42 of file Permission.php.
The documentation for this class was generated from the following file:
Permission.php