Yii Access Control Lists: PmAclNode Class Reference
PmAclNode Class Reference
Implements path-materilization and node-specific logic for tree-operations.
Public Member Functions
__clone ()
branchNodeSubTree ($source, $destination)
Copies all children of $source recursively into $destination This branching is necessary because: If an AclObject is a child of another one, every AclNode of the parent object has to have one AclNode of the child AclObject as it's child (this is due to the lookup-mechanism this extension uses) If a new AclNode is created (for example because the parent object itself joins another object), the subtree of an existing node is copied to the new node.
getOwnPath ()
Gets the path of this node including itself.
Protected Member Functions
generateDirectChildrenCondition ()
Generates the condition matching the direct AclNodes of this node.
generateDirectParentCondition ()
Generates the condition matching the direct parent AclNodes of this node.
removeFullRecursively ()
Removes all child-nodes and their associated permissions.
takeOverPermissions ($node)
This method copies all permissions assigned to another AclNode-Object of the same AclObject.
Detailed Description
Implements path-materilization and node-specific logic for tree-operations.
Author:
dispy <dispyfree@googlemail.com> LGPLv2
Definition at line 9 of file PmAclNode.php.
Member Function Documentation
PmAclNode::__clone ()
Reimplemented from AclNode.
Definition at line 122 of file PmAclNode.php.
PmAclNode::branchNodeSubTree ($ source, $ destination)
Copies all children of $source recursively into $destination This branching is necessary because: If an AclObject is a child of another one, every AclNode of the parent object has to have one AclNode of the child AclObject as it's child (this is due to the lookup-mechanism this extension uses) If a new AclNode is created (for example because the parent object itself joins another object), the subtree of an existing node is copied to the new node.
In fact "copied" is the wrong term, because each node isn't cloned but a surrogate is created which is in fact another object - but a node of the same AclObject having the same children as the original one.
public
Parameters:
AclNode source
AclNode destination
Return values:
int the number of branched nodes (recursive!)
Reimplemented from AclNode.
Definition at line 70 of file PmAclNode.php.
References $source, and PmPathManager\appendToPath().
PmAclNode::generateDirectChildrenCondition () [protected]
Generates the condition matching the direct AclNodes of this node.
Return values:
array(string,array) the first is the condition, the second one the params
Reimplemented from AclNode.
Definition at line 90 of file PmAclNode.php.
References PmPathManager\appendToPath().
PmAclNode::generateDirectParentCondition () [protected]
Generates the condition matching the direct parent AclNodes of this node.
Return values:
array(string,array) the first is the condition, the second one the params
Reimplemented from AclNode.
Definition at line 102 of file PmAclNode.php.
References PmPathManager\getParentPath().
PmAclNode::getOwnPath ()
Gets the path of this node including itself.
Return values:
string the own path
Definition at line 117 of file PmAclNode.php.
References PmPathManager\appendToPath().
PmAclNode::removeFullRecursively () [protected]
Removes all child-nodes and their associated permissions.
Exceptions:
RuntimeException
Reimplemented from AclNode.
Definition at line 15 of file PmAclNode.php.
References PmPathManager\appendToPath(), Util\getDataBaseType(), PmPathManager\getSeparator(), and Permission\model().
PmAclNode::takeOverPermissions ($ node) [protected]
This method copies all permissions assigned to another AclNode-Object of the same AclObject.
Parameters:
AclNode the node to take the permissions from
Reimplemented from AclNode.
Definition at line 42 of file PmAclNode.php.
The documentation for this class was generated from the following file:
PmAclNode.php