Yii Access Control Lists: Action Class Reference
Action Class Reference
Public Member Functions
__toString ()
attributeLabels ()
relations ()
rules ()
search ()
Retrieves a list of models based on the current search/filter conditions.
tableName ()
Static Public Member Functions
static model ($className=__CLASS__)
Returns the static model of the specified AR class.
static translateActions ($obj, $actions)
Translates the gibven actions into valid actions.
Public Attributes
$id
$name
Static Protected Member Functions
static getAllStringActions ()
Fetches all actions from the database and returns them in an indexed array.
static processActionOperation ($posMinus, $posPlus, $actions)
Processes the next operation on the actions and returns them.
static translateStringActions ($actions)
Processes the given actions.
Detailed Description
Definition at line 21 of file Action.php.
Member Function Documentation
Action::__toString ()
Definition at line 174 of file Action.php.
Action::attributeLabels ()
Return values:
array customized attribute labels (name=>label)
Definition at line 231 of file Action.php.
static Action::getAllStringActions () [static, protected]
Fetches all actions from the database and returns them in an indexed array.
Return values:
array[string] the actinos
Definition at line 164 of file Action.php.
References model().
static Action::model ($ className = __CLASS__) [static]
Returns the static model of the specified AR class.
Parameters:
string $className active record class name.
Return values:
Action the static model class
Definition at line 187 of file Action.php.
Referenced by ListArosAction\extendInformation(), RestrictedActiveRecord\generateAccessCheck(), RestrictedActiveRecordBehavior\generateAccessCheck(), SetPermissionAction\getAction(), getAllStringActions(), RestrictedActiveRecord\getDirectlyPermitted(), and RestrictedActiveRecordBehavior\getDirectlyPermitted().
static Action::processActionOperation ($ posMinus, $ posPlus, $ actions) [static, protected]
Processes the next operation on the actions and returns them.
Parameters:
int $posMinus pos of the next minus-symbol in the string
int $posPlus pos of the next plus-symbol in the string
string $actions the action-string
Return values:
array[string] the actions
Definition at line 135 of file Action.php.
References translateStringActions().
Referenced by translateStringActions().
Action::relations ()
Return values:
array relational rules.
Definition at line 220 of file Action.php.
Action::rules ()
Return values:
array validation rules for model attributes.
Definition at line 203 of file Action.php.
Action::search ()
Retrieves a list of models based on the current search/filter conditions.
Return values:
CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
Definition at line 244 of file Action.php.
Action::tableName ()
Return values:
string the associated database table name
Definition at line 195 of file Action.php.
static Action::translateActions ($ obj, $ actions) [static]
Translates the gibven actions into valid actions.
Parameters:
mixed $obj the object to perform the permissions on (either CActiveRecord or a string or an ACL-Object
mixed $actions may be a string or an array
Definition at line 32 of file Action.php.
References translateStringActions().
Referenced by PmAro\deny(), ActionMeta\finalActionMeta(), RestrictedActiveRecord\getDirectlyPermitted(), RestrictedActiveRecordBehavior\getDirectlyPermitted(), PmAro\grant(), PmAro\may(), and RestrictedActiveRecord\mayGenerally().
static Action::translateStringActions ($ actions) [static, protected]
Processes the given actions.
Parameters:
mixed $actions string or array of actions
Definition at line 92 of file Action.php.
References processActionOperation().
Referenced by processActionOperation(), and translateActions().
Member Data Documentation
Action::$id
Definition at line 24 of file Action.php.
Action::$name
Definition at line 25 of file Action.php.
The documentation for this class was generated from the following file:
Action.php