Yii Access Control Lists: ActionMeta Class Reference
ActionMeta Class Reference
ActionMeta Class File.
Static Public Member Functions
static allowedActions ()
The global allowed Actions Please note that this restricts the actions which are being accessible using the management tools at all.
static finalActionMeta ($model, $applyList=true)
This returns the Action-Meta, taking into account all the three settings above (you can disable the listing, see second parameter)
static getActionMeta ()
The global Action-Metadata required: name optional: short_desc long_desc enabled_img disabled_img.
static listActions ()
The global listActions.
Detailed Description
ActionMeta Class File.
This class stores general MetaData for the actions This metaData includes a human-readable name for each action, a short and possibly also a long Description. In addition to that you can specify two images for the active and disabled style. The metaData can be invididually overwritten in each model
Author:
dispy <dispyfree@googlemail.com> LGPLv2
Definition at line 15 of file ActionMeta.php.
Member Function Documentation
static ActionMeta::allowedActions () [static]
The global allowed Actions Please note that this restricts the actions which are being accessible using the management tools at all.
The list Actions only indicate what the client-side will display, but as you can do your own, manual ajax-requests this will stonewall any attempts to violate permissions
Note that it doesn't make sense to list actions which are not permitted anyway, that's why they're automatically removed
See also:
listActions
Return values:
string
Definition at line 84 of file ActionMeta.php.
static ActionMeta::finalActionMeta ($ model, $ applyList = true) [static]
This returns the Action-Meta, taking into account all the three settings above (you can disable the listing, see second parameter)
Parameters:
string Name of the CActiveRerd-Model
boolean Whether to return only the listable actions
Return values:
array
Definition at line 95 of file ActionMeta.php.
References getActionMeta(), and Action\translateActions().
Referenced by ListActionsAction\internalRun().
static ActionMeta::getActionMeta () [static]
The global Action-Metadata required: name optional: short_desc long_desc enabled_img disabled_img.
Return values:
array
Definition at line 28 of file ActionMeta.php.
Referenced by finalActionMeta(), and ListActionsAction\internalRun().
static ActionMeta::listActions () [static]
The global listActions.
See also:
all allowedActions
Return values:
string
Definition at line 68 of file ActionMeta.php.
The documentation for this class was generated from the following file:
ActionMeta.php