Yii Access Control Lists: AutocompleteAction Class Reference
AutocompleteAction Class Reference
Public Member Functions
internalRun ()
run ()
Protected Member Functions
getDescriptiveValue ($model)
getObjects ($model, $descriptiveValue, $term)
Detailed Description
Definition at line 3 of file AutoCompleteAction.php.
Member Function Documentation
AutocompleteAction::getDescriptiveValue ($ model) [protected]
Definition at line 39 of file AutoCompleteAction.php.
Referenced by internalRun().
AutocompleteAction::getObjects ($ model, $ descriptiveValue, $ term) [protected]
Definition at line 32 of file AutoCompleteAction.php.
Referenced by internalRun().
AutocompleteAction::internalRun ()
Definition at line 9 of file AutoCompleteAction.php.
References getDescriptiveValue(), and getObjects().
AutocompleteAction::run ()
Definition at line 5 of file AutoCompleteAction.php.
The documentation for this class was generated from the following file:
AutoCompleteAction.php