Yii Access Control Lists: AclObjectBehavior Class Reference
AclObjectBehavior Class Reference
RequestingActiveRecordBehavior Class File.
Public Member Functions
afterSave (&$evt)
This method takes care that autoJoins are done.
is ($obj)
Checks whether this object is somehow a child of the given object.
join ($obj)
Joins the given object (now called: group)
leave ($obj)
Leaves the given group.
Protected Member Functions
getAutoJoins ($obj)
Returns a list of identifiers to join for the given object.
getType ()
Overwrite this method to return the actual class Name.
loadObject ()
Loads the associated Object.
performAutoJoins ()
Performs the autoJoins defined in the configuration or by the model NOTE: This method will bypass any restrictions on joins.
Protected Attributes
mixed $_obj = NULL
This will hold the actual aco - object this behavior is linked to the acl-object.
Detailed Description
RequestingActiveRecordBehavior Class File.
This class serves as the behavior to be used for all "actors" in the program who have to per form actions on other objects
Author:
dispy <dispyfree@googlemail.com> LGPLv2
Definition at line 12 of file AclObjectBehavior.php.
Member Function Documentation
AclObjectBehavior::afterSave (&$ evt)
This method takes care that autoJoins are done.
Parameters:
type $evt
Definition at line 68 of file AclObjectBehavior.php.
References performAutoJoins().
AclObjectBehavior::getAutoJoins ($ obj) [protected]
Returns a list of identifiers to join for the given object.
Parameters:
CActiveRecord $obj the object to fetch the autojoins for
Return values:
array an array of identifiers to join
Definition at line 98 of file AclObjectBehavior.php.
References Strategy\get(), and getType().
Referenced by performAutoJoins().
AclObjectBehavior::getType () [abstract, protected]
Overwrite this method to return the actual class Name.
Return values:
either "Aro" or "Aco"
Reimplemented in RestrictedActiveRecordBehavior, and RequestingActiveRecordBehavior.
Referenced by getAutoJoins(), and loadObject().
AclObjectBehavior::is ($ obj)
Checks whether this object is somehow a child of the given object.
Parameters:
mixed $obj
Return values:
boolean
Definition at line 58 of file AclObjectBehavior.php.
References loadObject().
AclObjectBehavior::join ($ obj)
Joins the given object (now called: group)
Parameters:
mixed $obj
Return values:
boolean
Definition at line 38 of file AclObjectBehavior.php.
References loadObject().
AclObjectBehavior::leave ($ obj)
Leaves the given group.
Parameters:
mixed $obj
Return values:
boolean
Definition at line 48 of file AclObjectBehavior.php.
References loadObject().
AclObjectBehavior::loadObject () [protected]
Loads the associated Object.
Exceptions:
RuntimeException
Reimplemented in RequestingActiveRecordBehavior.
Definition at line 29 of file AclObjectBehavior.php.
References getType(), and AclObject\loadObjectStatic().
Referenced by RestrictedActiveRecordBehavior\getPositionCheck(), is(), join(), and leave().
AclObjectBehavior::performAutoJoins () [protected]
Performs the autoJoins defined in the configuration or by the model NOTE: This method will bypass any restrictions on joins.
Definition at line 82 of file AclObjectBehavior.php.
References getAutoJoins().
Referenced by afterSave().
Member Data Documentation
mixed AclObjectBehavior::$_obj = NULL [protected]
This will hold the actual aco - object this behavior is linked to the acl-object.
Definition at line 17 of file AclObjectBehavior.php.
The documentation for this class was generated from the following file:
AclObjectBehavior.php