Yii Access Control Lists: RestrictedActiveRecord Class Reference
RestrictedActiveRecord Class Reference
RestrictedActiveRecord Class File This class serves as a base-class for all the objects which have to control their access.
Public Member Functions
afterSave ()
This method takes care to assign individual rights to newly created objects.
beforeDelete ()
This method checks whether the user has the right to delete the current record.
beforeSave ()
This method checks whether the user has the right to update the current record By default, it's always allowed to create a new object.
find ($conditions= '', $params=array())
findAll ($conditions= '', $params=array())
findAllByAttributes ($attributes, $conditions= '', $params=array())
findAllByPk ($pk, $conditions= '', $params=array())
findAllBySQL ($sql, $params=array())
findByAttributes ($attributes, $conditions= '', $params=array())
findByPk ($pk, $conditions= '', $params=array())
findBySQL ($sql, $params=array())
getDirectlyPermitted ($actions= '*')
Gets the Aros who are directly (no inheritance!) permitted to perform one of the specified actions on this object.
grants ($permission)
Checks whether the current ARO has the given permission on this object.
Static Public Member Functions
static checkBirPermission ($condition, $params, $originalObjects)
Defining them statically is quite a mess, but that's what PHP is.
static getAutoPermissions ($obj)
static getUser ()
Fetches the Access Request-Object to use (either the current user or an object from self::inAttendance.
static mayGenerally ($aco, $perm)
Checks whether the user is generally allowed to perform the given permission(s) on the given object.
Static Public Attributes
static boolean $byPassCheck = false
This is used to temporarily disable the Access Check This may be needed if for example the user is a guest and has therefore no update-rights (he doesn't have an ARO representation) on his own objects.
static $defaultOptions
static mixed $inAttendance = NULL
This variable can be used to access the resource in attendance of another ARO-collection than the current user default is to NULL which means that the user denoted by Yii::app()->user is used for access checking.
static string $model = 'User'
The model to use for automatic access checing (as Aro-Collection).
static array[string] $possibleActions = NULL
This contains all possible actions for the objects of this class.
Protected Member Functions
generateAccessCheck ($conditions= '', $params=array(), $options=array())
The following functions generates the CDbCriteria necessary to filter all accessable rows The CDbCriteria is solely passsed to the wrapped methods.
Static Protected Member Functions
static areBusinessRulesFulfilled ($mode, $permission, $originalObjects)
Checks whether the business-rules attached to this permission are fulfilled.
static excludePaths ($mode, $condition)
This excludes the paths from the search criteria ($condition) according to the mode.
static getPermissionsWithBiz ($conditions, $params)
Finds all permissions including their associated objects (nodes and collections) Uses the configuration to determine in which direction(s) to fetch objects.
static translateMode ($mode)
Translates the given string to a list of modes to examine.
Detailed Description
RestrictedActiveRecord Class File This class serves as a base-class for all the objects which have to control their access.
Author:
dispy <dispyfree@googlemail.com> LGPLv2 This class is intended as a base for objects which have restrictions on their access It automatically checks, if the current user has the permissions to commit the regular CRUD-tasks
Definition at line 16 of file RestrictedActiveRecord.php.
Member Function Documentation
RestrictedActiveRecord::afterSave ()
This method takes care to assign individual rights to newly created objects.
Parameters:
CEvent $evt
Reimplemented in RestrictedTreeActiveRecord.
Definition at line 251 of file RestrictedActiveRecord.php.
References Strategy\getClass(), and getUser().
static RestrictedActiveRecord::areBusinessRulesFulfilled ($ mode, $ permission, $ originalObjects) [static, protected]
Checks whether the business-rules attached to this permission are fulfilled.
Parameters:
string $mode (either "aro" or "aco"
Permission $permission the permission to check
array An array of the original objects ('aro', 'aco')
Return values:
boolean true if they are fulfilled, false otherwise
Definition at line 503 of file RestrictedActiveRecord.php.
RestrictedActiveRecord::beforeDelete ()
This method checks whether the user has the right to delete the current record.
Definition at line 224 of file RestrictedActiveRecord.php.
References Strategy\getClass(), and getUser().
RestrictedActiveRecord::beforeSave ()
This method checks whether the user has the right to update the current record By default, it's always allowed to create a new object.
This object is automatically assigned to the user who created it with full permissions
Definition at line 199 of file RestrictedActiveRecord.php.
References getUser().
static RestrictedActiveRecord::checkBirPermission ($ condition, $ params, $ originalObjects) [static]
Defining them statically is quite a mess, but that's what PHP is.
See also:
PmAco Checks if the given permission is granted - includes business-rules
Parameters:
string $condition the query condition
array $params the attached parameters
array An array of the original objects ('aro', 'aco')
Definition at line 361 of file RestrictedActiveRecord.php.
References getPermissionsWithBiz().
Referenced by PmAro\may().
static RestrictedActiveRecord::excludePaths ($ mode, $ condition) [static, protected]
This excludes the paths from the search criteria ($condition) according to the mode.
Parameters:
string $mode 'both', 'aro' or 'aco'
array $condition the $condition ('aroCondition', 'acoCondition')
Return values:
array the finished condition with excluded paths
Exceptions:
RuntimeException
If we search in one direction, we delete the paths and thus are able to check for business-rules making the path-entitlement up
Definition at line 469 of file RestrictedActiveRecord.php.
Referenced by getPermissionsWithBiz().
RestrictedActiveRecord::find ($ conditions = '', $ params = array())
Definition at line 125 of file RestrictedActiveRecord.php.
Referenced by findAll(), and findByAttributes().
RestrictedActiveRecord::findAll ($ conditions = '', $ params = array())
Definition at line 141 of file RestrictedActiveRecord.php.
References find(), and generateAccessCheck().
Referenced by findAllByAttributes().
RestrictedActiveRecord::findAllByAttributes ($ attributes, $ conditions = '', $ params = array())
Definition at line 145 of file RestrictedActiveRecord.php.
References findAll(), and generateAccessCheck().
Referenced by findAllByPk().
RestrictedActiveRecord::findAllByPk ($ pk, $ conditions = '', $ params = array())
Definition at line 149 of file RestrictedActiveRecord.php.
References findAllByAttributes(), and generateAccessCheck().
Referenced by findAllBySQL().
RestrictedActiveRecord::findAllBySQL ($ sql, $ params = array())
Definition at line 153 of file RestrictedActiveRecord.php.
References findAllByPk(), and generateAccessCheck().
RestrictedActiveRecord::findByAttributes ($ attributes, $ conditions = '', $ params = array())
Definition at line 129 of file RestrictedActiveRecord.php.
References find(), and generateAccessCheck().
Referenced by findByPk().
RestrictedActiveRecord::findByPk ($ pk, $ conditions = '', $ params = array())
Definition at line 133 of file RestrictedActiveRecord.php.
References findByAttributes(), and generateAccessCheck().
Referenced by findBySQL().
RestrictedActiveRecord::findBySQL ($ sql, $ params = array())
Definition at line 137 of file RestrictedActiveRecord.php.
References findByPk(), and generateAccessCheck().
RestrictedActiveRecord::generateAccessCheck ($ conditions = '', $ params = array(), $ options = array()) [protected]
The following functions generates the CDbCriteria necessary to filter all accessable rows The CDbCriteria is solely passsed to the wrapped methods.
Parameters:
sql $conditions the conditions being passed to the real method
array $params the params being passed to the real method
array $options options to be used by the method itself (keys: disableInheritance)
Return values:
CDbCriteria the criteria assuring that the user only gets what he has access to
Definition at line 52 of file RestrictedActiveRecord.php.
References $byPassCheck, $defaultOptions, Strategy\get(), Strategy\getClass(), getUser(), Permission\model(), and Action\model().
Referenced by findAll(), findAllByAttributes(), findAllByPk(), findAllBySQL(), findByAttributes(), findByPk(), and findBySQL().
static RestrictedActiveRecord::getAutoPermissions ($ obj) [static]
Definition at line 270 of file RestrictedActiveRecord.php.
Referenced by RestrictedActiveRecordBehavior\afterSave().
RestrictedActiveRecord::getDirectlyPermitted ($ actions = '*')
Gets the Aros who are directly (no inheritance!) permitted to perform one of the specified actions on this object.
Parameters:
mixed $actions the actions to be considered
Return values:
array All of the objects which have one of the permissions
Definition at line 163 of file RestrictedActiveRecord.php.
References Util\generateInStatement(), Strategy\getClass(), AclObject\loadObjectStatic(), Permission\model(), Action\model(), and Action\translateActions().
static RestrictedActiveRecord::getPermissionsWithBiz ($ conditions, $ params) [static, protected]
Finds all permissions including their associated objects (nodes and collections) Uses the configuration to determine in which direction(s) to fetch objects.
Parameters:
array $conditions ("aroCondition" and "acoCondition")
array $params
Return values:
array ["aro" =>Permissions, "aco" => Permissions, "both" => Permissions] Where aro and aco indicate in which direction to check for business rules
Definition at line 383 of file RestrictedActiveRecord.php.
References excludePaths(), Util\generateInStatement(), Strategy\get(), BusinessRules\listBusinessAliases(), Permission\model(), and translateMode().
Referenced by checkBirPermission().
static RestrictedActiveRecord::getUser () [static]
Fetches the Access Request-Object to use (either the current user or an object from self::inAttendance.
See also:
inAttendance
Return values:
AclObject
Exceptions:
RuntimeException
Definition at line 297 of file RestrictedActiveRecord.php.
References Strategy\getClass(), and AclObject\loadObjectsStatic().
Referenced by afterSave(), RestrictedActiveRecordBehavior\afterSave(), beforeDelete(), RestrictedActiveRecordBehavior\beforeDelete(), beforeSave(), RestrictedActiveRecordBehavior\beforeSave(), PmAro\checkPermissionChange(), PmAclObject\checkRelationChange(), generateAccessCheck(), RestrictedActiveRecordBehavior\generateAroPositionCheck(), grants(), RestrictedActiveRecordBehavior\grants(), ExtAccessRule\isRoleMatched(), and mayGenerally().
RestrictedActiveRecord::grants ($ permission)
Checks whether the current ARO has the given permission on this object.
Parameters:
string $permission
Definition at line 280 of file RestrictedActiveRecord.php.
References getUser().
static RestrictedActiveRecord::mayGenerally ($ aco, $ perm) [static]
Checks whether the user is generally allowed to perform the given permission(s) on the given object.
See also:
"enableGeneralPermissions" config.php of the currenctly active strategy
Parameters:
mixed $aco the object to perform the action on (either a string or a class)
mixed $permthe permission to perform
Definition at line 317 of file RestrictedActiveRecord.php.
References Strategy\get(), getUser(), and Action\translateActions().
Referenced by RestrictedActiveRecordBehavior\beforeDelete(), RestrictedActiveRecordBehavior\generateAccessCheck(), and PmAro\may().
static RestrictedActiveRecord::translateMode ($ mode) [static, protected]
Translates the given string to a list of modes to examine.
Parameters:
string $mode 'all', 'both', 'aro', 'aco'
Return values:
array
Exceptions:
RuntimeException
Definition at line 435 of file RestrictedActiveRecord.php.
Referenced by getPermissionsWithBiz().
Member Data Documentation
boolean RestrictedActiveRecord::$byPassCheck = false [static]
This is used to temporarily disable the Access Check This may be needed if for example the user is a guest and has therefore no update-rights (he doesn't have an ARO representation) on his own objects.
Definition at line 22 of file RestrictedActiveRecord.php.
Referenced by generateAccessCheck(), and RestrictedActiveRecordBehavior\generateAccessCheck().
RestrictedActiveRecord::$defaultOptions [static]
Initial value:
 array(
        'disableInheritance' => false,
    )
Definition at line 40 of file RestrictedActiveRecord.php.
Referenced by generateAccessCheck(), and RestrictedActiveRecordBehavior\generateAccessCheck().
mixed RestrictedActiveRecord::$inAttendance = NULL [static]
This variable can be used to access the resource in attendance of another ARO-collection than the current user default is to NULL which means that the user denoted by Yii::app()->user is used for access checking.
Definition at line 28 of file RestrictedActiveRecord.php.
string RestrictedActiveRecord::$model = 'User' [static]
The model to use for automatic access checing (as Aro-Collection).
Default: "User"
Definition at line 32 of file RestrictedActiveRecord.php.
Referenced by ExtAccessRule\isRoleMatched().
array [string] RestrictedActiveRecord::$possibleActions = NULL [static]
This contains all possible actions for the objects of this class.
All other actions will never be granted and always denied upon inquiry. Example: array('update', 'read') << all other action are not available
Definition at line 39 of file RestrictedActiveRecord.php.
The documentation for this class was generated from the following file:
RestrictedActiveRecord.php