Yii Access Control Lists: BusinessRules Class Reference
BusinessRules Class Reference
This file contains all the Business-Rules.
Static Public Member Functions
static fulfillsBusinessRule ($rule, $aro, $aco, $action)
Checks whether the given aro is has the given rule regarding the given aco and action.
static isa1 ($aro, $aco, $action)
prototype: public static function isRule(arr('child' => .., 'father' => ..), arr('child' => .., 'father' => ..), string) public static function isRule($aro, $aco, $action)
static isb1 ($aro, $aco, $action)
static listBusinessAliases ()
Static Public Attributes
static array $ruleMap = array()
If you have a rule named "Rule", you can define it in two ways: a) a public static function isRule of this class b) an entry "isRule" => "myFunc" where myFunc is a static function in this class ruleName => functionName.
Detailed Description
This file contains all the Business-Rules.
Author:
dispy <dispyfree@googlemail.com> LGPLv2
Definition at line 8 of file BusinessRules.php.
Member Function Documentation
static BusinessRules::fulfillsBusinessRule ($ rule, $ aro, $ aco, $ action) [static]
Checks whether the given aro is has the given rule regarding the given aco and action.
Parameters:
string $rule an action (special action: "is" for inheritance-checks)
array $aro an instance of the aro (either CActiveRecord or RGroup)
array $aco an instance of the aco (either CactiveRecord or CGroup)
string $action the action to be performed
Return values:
boolean
Definition at line 45 of file BusinessRules.php.
Referenced by PmAco\callSpecificBusinessRule(), and PmAro\callSpecificBusinessRule().
static BusinessRules::isa1 ($ aro, $ aco, $ action) [static]
prototype: public static function isRule(arr('child' => .., 'father' => ..), arr('child' => .., 'father' => ..), string) public static function isRule($aro, $aco, $action)
Definition at line 27 of file BusinessRules.php.
static BusinessRules::isb1 ($ aro, $ aco, $ action) [static]
Definition at line 31 of file BusinessRules.php.
static BusinessRules::listBusinessAliases () [static]
Return values:
array all the used aliases
Definition at line 58 of file BusinessRules.php.
Referenced by RestrictedActiveRecord\getPermissionsWithBiz(), and PmAclObject\is().
Member Data Documentation
array BusinessRules::$ruleMap = array() [static]
If you have a rule named "Rule", you can define it in two ways: a) a public static function isRule of this class b) an entry "isRule" => "myFunc" where myFunc is a static function in this class ruleName => functionName.
Definition at line 16 of file BusinessRules.php.
The documentation for this class was generated from the following file:
BusinessRules.php