Yii Access Control Lists: RequestingActiveRecordBehavior Class Reference
RequestingActiveRecordBehavior Class Reference
RequestingActiveRecordBehavior Class File.
Public Member Functions
afterSave ($event)
This method takes care to associate an ARO-collection with this one.
beforeDelete ($event)
This method takes care that every associated ACL-objects are properly removed.
deny ($obj, $actions)
Denies the object denoted by the $obj-identifier the given actions.
grant ($obj, $actions, $byPassCheck=false)
Grants the object denoted by the $obj-identifier the given actions.
may ($obj, $action)
Looks up if the user is granted a specific action to the given object.
Protected Member Functions
getType ()
Overwrite this method to return the actual class Name.
loadObject ()
Loads the associated Object this method must be overwritten because we have additional checks here.
Detailed Description
RequestingActiveRecordBehavior Class File.
This class serves as the behavior to be used for all "actors" in the program who have to per form actions on other objects
Author:
dispy <dispyfree@googlemail.com> LGPLv2
Definition at line 14 of file RequestingActiveRecordBehavior.php.
Member Function Documentation
RequestingActiveRecordBehavior::afterSave ($ event)
This method takes care to associate an ARO-collection with this one.
Parameters:
CEvent $evt
Definition at line 90 of file RequestingActiveRecordBehavior.php.
References Strategy\getClass().
RequestingActiveRecordBehavior::beforeDelete ($ event)
This method takes care that every associated ACL-objects are properly removed.
Definition at line 105 of file RequestingActiveRecordBehavior.php.
References Strategy\getClass().
RequestingActiveRecordBehavior::deny ($ obj, $ actions)
Denies the object denoted by the $obj-identifier the given actions.
Parameters:
type $obj the object identifier
array $actions the actions to deny
Return values:
bool
Definition at line 80 of file RequestingActiveRecordBehavior.php.
References loadObject().
RequestingActiveRecordBehavior::getType () [protected]
Overwrite this method to return the actual class Name.
Return values:
either "Aro" or "Aco"
Reimplemented from AclObjectBehavior.
Definition at line 20 of file RequestingActiveRecordBehavior.php.
Referenced by loadObject().
RequestingActiveRecordBehavior::grant ($ obj, $ actions, $ byPassCheck = false)
Grants the object denoted by the $obj-identifier the given actions.
Parameters:
type $obj the object identifier
array $actions the actions to grant
bool $byPassCheck Whether to bypass the additional grant-check
Return values:
bool
Definition at line 69 of file RequestingActiveRecordBehavior.php.
References loadObject().
RequestingActiveRecordBehavior::loadObject () [protected]
Loads the associated Object this method must be overwritten because we have additional checks here.
Exceptions:
RuntimeException
Reimplemented from AclObjectBehavior.
Definition at line 29 of file RequestingActiveRecordBehavior.php.
References Strategy\get(), Strategy\getClass(), and getType().
Referenced by deny(), grant(), and may().
RequestingActiveRecordBehavior::may ($ obj, $ action)
Looks up if the user is granted a specific action to the given object.
Parameters:
string | array $obj The object to be checked
string $action the action to be performed
Return values:
bool true if access is granted, false otherwise
Definition at line 57 of file RequestingActiveRecordBehavior.php.
References loadObject().
The documentation for this class was generated from the following file:
RequestingActiveRecordBehavior.php