Yii Access Control Lists: AclObject Class Reference
AclObject Class Reference
AclObject Interface File This is the base interfasce for AclObjects defining the most basic operations.
Public Member Functions
addPositionCheck ($positions, $type, $table= 't', $dir= 'asc', $fieldPostFix= '_path')
$dir = 'asc': Builds a single SQL-statement comprising all given positions and their parents This SQL-statement will match all those rows being located above the given positions including themselves
afterSave ()
Processes post-saving tasks.
fetchComprisedPositions ()
Fetches and returns positions of all nodes of this object which denote them In this case, it's really easy because we've done that anyway :)
getAssociatedObject ()
Loads the associated object, if possible, and returns it.
getChildObjects ()
Fetches all child-objects and returns them in an array.
getDirectChildNodes (AclObject $child=NULL)
Returns all of the (direct) AclNodes whose parent AclNode is a node of this AclObject.
getDirectParentNodes (AclObject $parent=NULL)
Returns all of the (direct) AclNodes whose child AclNode is a node of this AclObject.
getFreeNodes ()
Returns all of the AclNodes of this object which do not have a parent yet.
getNodes ()
This method returns all AclNodes being associated with this.
getParentObjects ()
Fetches all parent-objects and returns them in an array.
is ($obj)
Checks whether this object is somehow a child of the given object.
join ($obj)
Joins the given object (now called: group)
leave ($obj)
Leaves the given group.
loadObject ($identifier, $model=NULL)
Just a convenient wrapper to loadObjects.
loadObjects ($identifier, $model=NULL, $onlyFirst=true)
Just a convenient wrapper to loadObjects.
Static Public Member Functions
static loadObjectsStatic ($identifier, $model=NULL, $onlyFirst=true)
This method is used to load Objects (either Aco or Aro) using convenient identifiers.
static loadObjectStatic ($identifier, $model)
Just a convenient wrapper to loadObjects.
Protected Member Functions
assureSafety (&$obj=NULL)
Assures that:
assureSaved ()
Reassures that all passed objects have been saved.
beforeIs (&$obj)
Callback being executed before every childhood-check Usage of this method allows common behavior for several strategies with respect to object transformations and a secure environment.
beforeJoin (&$obj)
Callback being executed before every join Usage of this method allows common behavior for several strategies with respect to object transformations and a secure environment.
beforeLeave (&$obj)
Callback being executed before every leave Usage of this method allows common behavior for several strategies with respect to object transformations and a secure environment.
createNode ($parent=NULL)
Creates a new node of this collection This new node will be a children of the given AclNode.
Detailed Description
AclObject Interface File This is the base interfasce for AclObjects defining the most basic operations.
Author:
dispy <dispyfree@googlemail.com> * LGPLv2
Definition at line 15 of file AclObject.php.
Member Function Documentation
AclObject::addPositionCheck ($ positions, $ type, $ table = 't', $ dir = 'asc', $ fieldPostFix = '_path') [abstract]
$dir = 'asc': Builds a single SQL-statement comprising all given positions and their parents This SQL-statement will match all those rows being located above the given positions including themselves
$dir = 'desc' The same, but with all the positions located below the given positions or equal to them.
Parameters:
array $positions All positions to include in our statement
string $type aco/aro
string $fieldPostfix the postfix of the field (default: "_path" (suitable for the fields in the permission-table)
string $table the table comprising the map between objects and permissions
Return values:
string the finished SQL-statement
Reimplemented in PmAclObject.
AclObject::afterSave ()
Processes post-saving tasks.
Definition at line 355 of file AclObject.php.
AclObject::assureSafety (&$ obj = NULL) [protected]
Assures that:
the object is of a proper class
all involved objects have been saved before they interact
Parameters:
AclObject $obj
Definition at line 398 of file AclObject.php.
Referenced by beforeIs(), beforeJoin(), and beforeLeave().
AclObject::assureSaved () [protected]
Reassures that all passed objects have been saved.
Definition at line 379 of file AclObject.php.
AclObject::beforeIs (&$ obj) [protected]
Callback being executed before every childhood-check Usage of this method allows common behavior for several strategies with respect to object transformations and a secure environment.
Parameters:
AclObject $obj
Definition at line 50 of file AclObject.php.
References assureSafety().
Referenced by PmAclObject\is().
AclObject::beforeJoin (&$ obj) [protected]
Callback being executed before every join Usage of this method allows common behavior for several strategies with respect to object transformations and a secure environment.
Parameters:
AclObject $obj
Definition at line 30 of file AclObject.php.
References assureSafety().
Referenced by PmAclObject\join().
AclObject::beforeLeave (&$ obj) [protected]
Callback being executed before every leave Usage of this method allows common behavior for several strategies with respect to object transformations and a secure environment.
Parameters:
AclObject $obj
Definition at line 40 of file AclObject.php.
References assureSafety().
Referenced by PmAclObject\leave().
AclObject::createNode ($ parent = NULL) [abstract, protected]
Creates a new node of this collection This new node will be a children of the given AclNode.
Parameters:
AclNode $parent parent of the new node, if NULL, it has no parent
Return values:
AclNode the new node
Reimplemented in PmAclObject.
AclObject::fetchComprisedPositions () [abstract]
Fetches and returns positions of all nodes of this object which denote them In this case, it's really easy because we've done that anyway :)
Return values:
array[string]
Reimplemented in PmAclObject.
AclObject::getAssociatedObject ()
Loads the associated object, if possible, and returns it.
Return values:
mixed NULL or a child of CActiveREcord
Definition at line 368 of file AclObject.php.
AclObject::getChildObjects ()
Fetches all child-objects and returns them in an array.
Return values:
array[AclObject] the child-objects
Definition at line 141 of file AclObject.php.
References Util\getDataBaseType(), and getDirectChildNodes().
AclObject::getDirectChildNodes (AclObject $ child = NULL) [abstract]
Returns all of the (direct) AclNodes whose parent AclNode is a node of this AclObject.
If the $child AclObject is specified, only nodes having the given AclObject as owner will be returned.
public
Parameters:
AclObject child
Integer
Return values:
array[AclNode]
Reimplemented in PmAclObject.
Referenced by getChildObjects().
AclObject::getDirectParentNodes (AclObject $ parent = NULL) [abstract]
Returns all of the (direct) AclNodes whose child AclNode is a node of this AclObject.
If the $child AclObject is specified, only nodes having the given AclObject as owner will be returned.
public
Parameters:
AclObject child
Integer
Return values:
array[AclNode]
Reimplemented in PmAclObject.
AclObject::getFreeNodes () [abstract]
Returns all of the AclNodes of this object which do not have a parent yet.
public
Parameters:
AclObject object
Return values:
array[AclNode]
Reimplemented in PmAclObject.
AclObject::getNodes ()
This method returns all AclNodes being associated with this.
public
Parameters:
AclObject object
Return values:
array[AclNode]
Definition at line 346 of file AclObject.php.
References Util\getNodeNameOfObject().
Referenced by PmAro\deny(), and PmAro\grant().
AclObject::getParentObjects ()
Fetches all parent-objects and returns them in an array.
Return values:
array[AclObject] the parent-objects
Definition at line 159 of file AclObject.php.
References Util\getDataBaseType().
AclObject::is ($ obj) [abstract]
Checks whether this object is somehow a child of the given object.
Parameters:
mixed $obj
Return values:
boolean
Reimplemented in PmAclObject.
AclObject::join ($ obj) [abstract]
Joins the given object (now called: group)
Parameters:
mixed $obj
Return values:
boolean
AclObject::leave ($ obj) [abstract]
Leaves the given group.
Parameters:
mixed $obj
Return values:
boolean
AclObject::loadObject ($ identifier, $ model = NULL)
Just a convenient wrapper to loadObjects.
Parameters:
mixed $identifier The Identifier denoting the associated row in the ACL-system.
string $model - the class-Name of the expected object (Aro or Aco)
Definition at line 187 of file AclObject.php.
Referenced by PmAro\deny(), PmAro\grant(), and PmAro\may().
AclObject::loadObjects ($ identifier, $ model = NULL, $ onlyFirst = true)
Just a convenient wrapper to loadObjects.
Parameters:
mixed $identifier The Identifier denoting the associated row in the ACL-system.
string $model - the class-Name of the expected object (Aro or Aco)
Definition at line 198 of file AclObject.php.
static AclObject::loadObjectsStatic ($ identifier, $ model = NULL, $ onlyFirst = true) [static]
This method is used to load Objects (either Aco or Aro) using convenient identifiers.
Parameters:
mixed $identifier The Identifier denoting the associated row in the ACL-system. Supported identifiers: 1) Array syntax: array('model' => 'MyModel', 'foreign_key' => myId) e.g.: model => User, foreign_key => the ID of the user (presumably AUTO_INCREMENT INT from the user row) 2) alias syntax: "MyAlias" e.g.: "Visitors", "Admins", "Authors" 3) direct syntax: pass your object derived from CActiveRecord directly e.g.: loadObject(User::model()->find(....)) This will be automatically resolved to the first syntax. Please be aware that auto-creation of associated ACL-objects only happens if the strict-mode is disabled So if you pass a new object which has no corresponding aco/aro-row, this will lead to an exception if the strict-mode is enabled. 4) Of course, you can pass the finished object directly. As many methods call this method without check, this is natural.
string $model - the class-Name of the expected object (Aro or Aco)
boolean $onlyFirst Determines whether to fetch only the first matching object, or all of them.
Return values:
type
Try to get the "highest" object Why? objects are firstly always resolved using their CActiveRecord - properties. To retain consistency, we have to use this record, if possible (otherwise, we'd probably end up with a database entry of model "RGroup" and another one with the real model name!
If there's no associated model, this will always be resolved to the real class Name and no model name => consistency retained
Definition at line 226 of file AclObject.php.
References Strategy\get(), Util\getByIdentifierGraceful(), Strategy\getClass(), and Util\getDataBaseType().
Referenced by RestrictedTreeActiveRecordBehavior\afterSave(), and RestrictedActiveRecord\getUser().
static AclObject::loadObjectStatic ($ identifier, $ model) [static]
Just a convenient wrapper to loadObjects.
Parameters:
mixed $identifier The Identifier denoting the associated row in the ACL-system.
string $model - the class-Name of the expected object (Aro or Aco)
Definition at line 178 of file AclObject.php.
Referenced by RestrictedActiveRecord\getDirectlyPermitted(), RestrictedActiveRecordBehavior\getDirectlyPermitted(), PmAclObject\is(), PmAclObject\join(), PmAclObject\leave(), and AclObjectBehavior\loadObject().
The documentation for this class was generated from the following file:
AclObject.php