Yii Access Control Lists: RestrictedActiveRecordBehavior Class Reference
RestrictedActiveRecordBehavior Class Reference
RestrictedActiveRecordBehavior Class File This class serves as a behavior for all the objects which have to control their access.
Public Member Functions
afterSave ($event)
This method takes care to assign individual rights to newly created objects.
beforeDelete ($event)
This method checks whether the user has the right to delete the current record.
beforeSave ($event)
This method checks whether the user has the right to update the current record By default, it's always allowed to create a new object.
generateAccessCheck ($conditions= '', $params=array(), $options=array())
The following functions generates the CDbCriteria necessary to filter all accessable rows The CDbCriteria is solely passsed to the wrapped methods.
getDirectlyPermitted ($actions= '*')
Gets the Aros who are directly (no inheritance!) permitted to perform one of the specified actions on this object.
getId ()
Returns the static counter.
getUniqueName ($table)
generates a name unique to this Behavior-instance
grants ($permission)
Checks whether the current ARO has the given permission on this object.
Static Public Member Functions
static addGroupRestriction ($relation, $restr)
This method will add a criteria to the next query, which limits the resultset to a subset which fulfills the given group-conditions.
static recursiveAddGroupRestriction ($relation, $restr)
Prepares the group-restriction recursively.
Static Public Attributes
static array $criteria = array()
Temporary CDbCriteria merged with the given one this is used to pass certain things directly to this behavior because the regular CDbCriteria isn't passed array('relation' => array('key1' => ..., 'key2' => ...))
Protected Member Functions
considerExtraCriteria ($currentCriteria)
This method merges this criteria with additional criteria for this relation provided by the user and takes care that table placeholders are replaced.
generateAroPositionCheck ($permissionTable)
Generates the check for the positions of the aro.
generateGeneralPositionCheck ($permissionTable)
Generates a general permission check, applying also if the aco is somewhere between it's general equivalent.
getType ()
Overwrite this method to return the actual class Name.
translatePlaceholders ($criteria)
It's too clumsy for the developer to cope with the unique tables this query will create.
Static Protected Member Functions
static getPositionCheck ($obj)
Generates a condition-check for the given object, so that all of the objects matched by it are the object itself or its children.
Static Protected Attributes
static int $counter = 0
As there may be joins with several restricted models, we have to distinguish the tables in the joins.
Detailed Description
RestrictedActiveRecordBehavior Class File This class serves as a behavior for all the objects which have to control their access.
Author:
dispy <dispyfree@googlemail.com> LGPLv2 This class is intended tobe used as a behavior for objects which have restrictions on their access It automatically checks, if the current user has the permissions to commit the regular CRUD-tasks
Definition at line 17 of file RestrictedActiveRecordBehavior.php.
Member Function Documentation
static RestrictedActiveRecordBehavior::addGroupRestriction ($ relation, $ restr) [static]
This method will add a criteria to the next query, which limits the resultset to a subset which fulfills the given group-conditions.
The relation is the name of the relation you use in your relations definition in the model, if it's the accessed model itself, the relation is 't'.
Structure of the Restriction: restriction := array('operator', [recursiveRestriction [,recursiveRestriction...]]); recursiveRestriction := aclIdentifier | array('operator', [recursiveRestriction [,recursiveRestriction ...]]) aclIdentifier = 'alias' | array('alias' => 'myAlias') | array('model' => 'myModel', 'foreign_key' => 'foreignKey') | any Instance of CActiveRecord operator := 'and' | 'not' | 'or
This is quite a theoretical definition. Let's get down to the code: array('and', 'Group1', array('not', 'Group2')); => This will yield all objects being in group1 but not group 2
Parameters:
string $relation Name of the invoked relation
array $restr the group-restrictions
Definition at line 329 of file RestrictedActiveRecordBehavior.php.
References recursiveAddGroupRestriction().
Referenced by Util\addGroupRestr(), and recursiveAddGroupRestriction().
RestrictedActiveRecordBehavior::afterSave ($ event)
This method takes care to assign individual rights to newly created objects.
Parameters:
CEvent $evt
Definition at line 526 of file RestrictedActiveRecordBehavior.php.
References RestrictedActiveRecord\getAutoPermissions(), Strategy\getClass(), and RestrictedActiveRecord\getUser().
RestrictedActiveRecordBehavior::beforeDelete ($ event)
This method checks whether the user has the right to delete the current record.
Definition at line 498 of file RestrictedActiveRecordBehavior.php.
References Strategy\getClass(), RestrictedActiveRecord\getUser(), and RestrictedActiveRecord\mayGenerally().
RestrictedActiveRecordBehavior::beforeSave ($ event)
This method checks whether the user has the right to update the current record By default, it's always allowed to create a new object.
This object is automatically assigned to the user who created it with full permissions
Definition at line 474 of file RestrictedActiveRecordBehavior.php.
References RestrictedActiveRecord\getUser().
RestrictedActiveRecordBehavior::considerExtraCriteria ($ currentCriteria) [protected]
This method merges this criteria with additional criteria for this relation provided by the user and takes care that table placeholders are replaced.
Parameters:
CDbCriteria $criteria the criteria to transform
Return values:
CDbCriteria the transformed criteria
Definition at line 261 of file RestrictedActiveRecordBehavior.php.
References translatePlaceholders().
Referenced by generateAccessCheck().
RestrictedActiveRecordBehavior::generateAccessCheck ($ conditions = '', $ params = array(), $ options = array())
The following functions generates the CDbCriteria necessary to filter all accessable rows The CDbCriteria is solely passsed to the wrapped methods.
Parameters:
sql $conditions the conditions being passed to the real method
array $params the params being passed to the real method
array $options options to be used by the method itself (keys: disableInheritance)
Return values:
CDbCriteria the criteria assuring that the user only gets what he has access to
Now, we need to place the where at the end of all conditions
Definition at line 67 of file RestrictedActiveRecordBehavior.php.
References RestrictedActiveRecord\$byPassCheck, $criteria, RestrictedActiveRecord\$defaultOptions, considerExtraCriteria(), generateAroPositionCheck(), generateGeneralPositionCheck(), Strategy\getClass(), getUniqueName(), RestrictedActiveRecord\mayGenerally(), Permission\model(), Action\model(), and Util\rep().
RestrictedActiveRecordBehavior::generateAroPositionCheck ($ permissionTable) [protected]
Generates the check for the positions of the aro.
Parameters:
string the name of the permission-table
Return values:
string the finished condition
Definition at line 207 of file RestrictedActiveRecordBehavior.php.
References Strategy\get(), Strategy\getClass(), and RestrictedActiveRecord\getUser().
Referenced by generateAccessCheck().
RestrictedActiveRecordBehavior::generateGeneralPositionCheck ($ permissionTable) [protected]
Generates a general permission check, applying also if the aco is somewhere between it's general equivalent.
Parameters:
string $permissionTable
Return values:
string the condition
Definition at line 240 of file RestrictedActiveRecordBehavior.php.
Referenced by generateAccessCheck().
RestrictedActiveRecordBehavior::getDirectlyPermitted ($ actions = '*')
Gets the Aros who are directly (no inheritance!) permitted to perform one of the specified actions on this object.
Parameters:
mixed $actions the actions to be considered
Return values:
array All of the objects which have one of the permissions
Definition at line 437 of file RestrictedActiveRecordBehavior.php.
References Util\generateInStatement(), Strategy\getClass(), AclObject\loadObjectStatic(), Permission\model(), Action\model(), and Action\translateActions().
RestrictedActiveRecordBehavior::getId ()
Returns the static counter.
See also:
$counter
Return values:
int the ID of this behavior-instance
Definition at line 39 of file RestrictedActiveRecordBehavior.php.
References $counter.
Referenced by getUniqueName().
static RestrictedActiveRecordBehavior::getPositionCheck ($ obj) [static, protected]
Generates a condition-check for the given object, so that all of the objects matched by it are the object itself or its children.
Parameters:
mixed $obj the object to generate the condition for
Return values:
string the condition
Definition at line 408 of file RestrictedActiveRecordBehavior.php.
References $counter, and AclObjectBehavior\loadObject().
Referenced by recursiveAddGroupRestriction().
RestrictedActiveRecordBehavior::getType () [protected]
Overwrite this method to return the actual class Name.
Return values:
either "Aro" or "Aco"
Reimplemented from AclObjectBehavior.
Definition at line 23 of file RestrictedActiveRecordBehavior.php.
RestrictedActiveRecordBehavior::getUniqueName ($ table)
generates a name unique to this Behavior-instance
Parameters:
string the tableName
Return values:
string the unique tableName
Definition at line 48 of file RestrictedActiveRecordBehavior.php.
References getId().
Referenced by generateAccessCheck(), and translatePlaceholders().
RestrictedActiveRecordBehavior::grants ($ permission)
Checks whether the current ARO has the given permission on this object.
Parameters:
string $permission
Definition at line 549 of file RestrictedActiveRecordBehavior.php.
References RestrictedActiveRecord\getUser().
static RestrictedActiveRecordBehavior::recursiveAddGroupRestriction ($ relation, $ restr) [static]
Prepares the group-restriction recursively.
Parameters:
string $relation name of the relation
array $restr the restriction in its array-santax
Return values:
string
Definition at line 351 of file RestrictedActiveRecordBehavior.php.
References addGroupRestriction(), and getPositionCheck().
Referenced by addGroupRestriction().
RestrictedActiveRecordBehavior::translatePlaceholders ($ criteria) [protected]
It's too clumsy for the developer to cope with the unique tables this query will create.
So we employ placeholders we'll simply replace
Parameters:
type $criteria
Definition at line 287 of file RestrictedActiveRecordBehavior.php.
References $criteria, and getUniqueName().
Referenced by considerExtraCriteria().
Member Data Documentation
int RestrictedActiveRecordBehavior::$counter = 0 [static, protected]
As there may be joins with several restricted models, we have to distinguish the tables in the joins.
That happens this way: tableName_$id The id is unique to every RestrictedActiveRecordBehavior-Instance.
Definition at line 32 of file RestrictedActiveRecordBehavior.php.
Referenced by getId(), and getPositionCheck().
array RestrictedActiveRecordBehavior::$criteria = array() [static]
Temporary CDbCriteria merged with the given one this is used to pass certain things directly to this behavior because the regular CDbCriteria isn't passed array('relation' => array('key1' => ..., 'key2' => ...))
Definition at line 57 of file RestrictedActiveRecordBehavior.php.
Referenced by generateAccessCheck(), and translatePlaceholders().
The documentation for this class was generated from the following file:
RestrictedActiveRecordBehavior.php