Yii Access Control Lists: SetPermissionAction Class Reference
SetPermissionAction Class Reference
Public Member Functions
internalRun ()
run ()
Protected Member Functions
getAction ($model, $permission)
getParameters ()
loadAcos ($objects)
loadAros ($model, $selection)
setPermission ($aro, $action, $mode, $acos)
Protected Attributes
$errors = array()
Detailed Description
Definition at line 3 of file SetPermissionAction.php.
Member Function Documentation
SetPermissionAction::getAction ($ model, $ permission) [protected]
Definition at line 59 of file SetPermissionAction.php.
References Action\model().
Referenced by getParameters().
SetPermissionAction::getParameters () [protected]
Definition at line 24 of file SetPermissionAction.php.
References getAction(), loadAcos(), and loadAros().
Referenced by internalRun().
SetPermissionAction::internalRun ()
Definition at line 11 of file SetPermissionAction.php.
References getParameters(), and setPermission().
SetPermissionAction::loadAcos ($ objects) [protected]
Definition at line 75 of file SetPermissionAction.php.
Referenced by getParameters().
SetPermissionAction::loadAros ($ model, $ selection) [protected]
Definition at line 42 of file SetPermissionAction.php.
Referenced by getParameters().
SetPermissionAction::run ()
Definition at line 5 of file SetPermissionAction.php.
SetPermissionAction::setPermission ($ aro, $ action, $ mode, $ acos) [protected]
Definition at line 104 of file SetPermissionAction.php.
Referenced by internalRun().
Member Data Documentation
SetPermissionAction::$errors = array() [protected]
Definition at line 9 of file SetPermissionAction.php.
The documentation for this class was generated from the following file:
SetPermissionAction.php